[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "3b3ac67c6ab3e092e0467e907ab31ae787cc8368"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2c84af163dbc83c6eb6a94a03d5c25f25b6b8623"}
