[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "06938f41396adaa68a919147b0f463f9d2f7245a"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2c84af163dbc83c6eb6a94a03d5c25f25b6b8623"}
