[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "f1a0492bcd7d3881ce93b1fba5e41e6ab3d02ce5"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "0ac694c04ab68428e65671f20cf0696280689b56"}
